### ISSUE TITLE
Throw error message if not match `id` on data

### ISSUE THREAD

**Issue by ufoo68** [jsBlackBelt/TheSportsDB#3]
For example, I tried this query (not match id). 

```
query {
    player(id:1) {
        name
    }
}
```

Then, I receive this error message.

```
Cannot read property 'map' of null
``` 

Probably, the user would not understand reason why happen the error message. I suggest throw this message if not match id on data.

```
Not match `id` on ${data}.
```

**Comment by sefininio** [comment]
Very valid points. Thanks for pointing it out and opening an issue!

However the approach in PR #4 is not a standard solution.
The GQL Spec builds on the response having data and/or errors. 

I agree the returned error is not very helpful or readable - it would be better to either return `null` as a valid response for an invalid `id`, or return a new `ApolloError`.

See the commit that closes this for more info.
